// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_dznwz8TvQ3yNUNpqTyo8OexVinDUqY',
    appId: '1:425414323039:web:300697316680d22866a4ea',
    messagingSenderId: '425414323039',
    projectId: 'tasks-16b0d',
    authDomain: 'tasks-16b0d.firebaseapp.com',
    storageBucket: 'tasks-16b0d.appspot.com',
    measurementId: 'G-LEB052Z4FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2k6T6IzLfoPLSQKVcBzKH_1JO7BJZew',
    appId: '1:425414323039:android:8881c70fdae62a8066a4ea',
    messagingSenderId: '425414323039',
    projectId: 'tasks-16b0d',
    storageBucket: 'tasks-16b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoIK_r-iydLTQ8POoee4LFzF5njYs5WA',
    appId: '1:425414323039:ios:023fa8b2ce25229e66a4ea',
    messagingSenderId: '425414323039',
    projectId: 'tasks-16b0d',
    storageBucket: 'tasks-16b0d.appspot.com',
    iosBundleId: 'com.example.task5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJoIK_r-iydLTQ8POoee4LFzF5njYs5WA',
    appId: '1:425414323039:ios:023fa8b2ce25229e66a4ea',
    messagingSenderId: '425414323039',
    projectId: 'tasks-16b0d',
    storageBucket: 'tasks-16b0d.appspot.com',
    iosBundleId: 'com.example.task5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_dznwz8TvQ3yNUNpqTyo8OexVinDUqY',
    appId: '1:425414323039:web:bc9460a0ddd3a90266a4ea',
    messagingSenderId: '425414323039',
    projectId: 'tasks-16b0d',
    authDomain: 'tasks-16b0d.firebaseapp.com',
    storageBucket: 'tasks-16b0d.appspot.com',
    measurementId: 'G-04CCZJ6HSB',
  );

}